INSERT INTO `san_pham` (`ma_sp`, `ten_sp`, `ma_hang`, `so_luong_ton`, `mo_ta`, `anh_minh_hoa`, `don_gia`, `ma_loai`) VALUES
('SP01', 'Dr-Namda Ketocho Well Shampoo', 'H004', 50, 'Kháng nấm, khuẩn, diệt ve, giữ ẩm cho Chó', 'SP05.jpg', 110000, 'LSP04'),
('SP010', 'Xương gặm đồ chơi cho chó - Đồ chơi 016', 'H002', 24, '[MÔ TẢ] Nhựa PP chống nhờn, không bám bẩn, làm sạch mảng bám trên răng\r\n [CÔNG DỤNG] \r\n>> Khi thú chơi và gặm sẽ làm sạch răng thú\r\n>> Chơi ném & bắt với thú\r\n>> Có chuông vui nhộn\r\n>>Chăm sóc thú tốt hơn', 'dc.jpg', 17900, 'LSP05'),
('SP011', 'Sữa cho mèo msbilac gold cat 100g', 'KH001', 33, 'với thành phần giàu chất dinh dưỡng, cân đối và rất dễ tiêu hóa tương tự sữa mẹ, \r\n\r\ncó tác dụng thay thế sữa mẹ trong trường hợp mèo mất sữa, kém sữa hoặc thiếu sữa do bầy con quá đông, \r\n\r\nđồng thời là nguồn bổ sung chất dinh dưỡng cho mèo còi cọc, chậm lớn', 'sua.jpg', 35000, 'LSP03'),
('SP012', 'Lồng đại không phụ kiện cho hamster, nhím, sóc,.', 'H003', 12, 'Thương hiệu No Brand, Loại động vật Thú cưng nhỏ ', 'long.jpg', 120000, 'LSP06'),
('SP013', 'Bình ti sữa cho chó mèo - phụ kiện thú cưng GENYO', 'H002', 35, 'Bình ti sữa cho chó mèo - phụ kiện thú cưng\r\n- Chó mèo mẹ mất sữa, ko đủ sữa nuôi con.\r\n- Chó mèo con cần thêm chất.\r\n- Chó mèo đang trong trời kỳ dưỡng bệnh cần uống sữa.\r\nBình ti sữa là vật dụng rất cần thiết dành cho người nuôi thú cưng.\r\nBộ sản phẩm có 2 loại:\r\n+ Bình 60ml gồm: 5 đầu ti silicon kích thước khác nhau + bình + que rửa bình + thông đầu ti\r\n+ Bình 150ml gồm: 2 đầu ti silicon + bình + que rửa bình + thông đầu ti', 'khb.jpg', 35000, 'LSP02'),
('SP014', 'BÁT ĂN CHỐNG TRÀN THỨC ĂN CHO CHÓ MÈO – BÁT ĂN 010', 'KH001', 22, '[GIỚI THIỆU] BÁT ĂN CHỐNG TRÀN THỨC ĂN CHO CHÓ MÈO – BÁT ĂN 008\r\n\r\n[MÔ TẢ] Thú cưng hiếu động sẽ làm rơi vãi thức ăn khi bạn cho chúng ăn, dụng cụ này sẽ giúp bạn không phải đi dọn thức ăn rơi vãi nữa.\r\n>> Phù hợp cho thú nhỏ đến lớn\r\n>> Nhỏ gọn, máng trơn giúp tránh được tình trạng thú nhai bát ăn', 'bat.jpg', 79000, 'LSP02'),
('SP02', 'Thức ăn cho mèo lớn dạng hạt vị cá ngừ 1.2kg', 'H003', 75, 'Xuất xứ: Thái Lan', 'SP04.jpg', 110000, 'LSP03'),
('SP03', 'Cát vệ sinh mèo McKelly 5L', 'H003', 55, 'Không bụi: Quạt thổi ầm ầm vẫn không có bụi bay.\r\n\r\nVón cục: Sau khi mèo đi vệ sinh, cục vón ném xa vẫn không vỡ vụn.\r\n\r\nKhử Mùi: Phản ứng hoá học Than hoạt tính (Hạt màu) khử mùi 100%\r\n\r\nKhông bết đáy như một chiếc chảo chống dính.\r\n\r\nChọn Mùi\r\nTáo\r\nDâu\r\nChanh\r\nCam\r\nCà Phê\r\nĐào', 'catmeo.jpg', 75000, 'LSP02'),
('SP05', 'Vòng đeo trị ve rận bọ chét cho mèo - BIOLINE', 'H003', 20, 'GIỚI THIỆU] Vòng đeo trị ve rận bọ chét chó mèo - BIOLINE\r\n[CÔNG DỤNG] dùng cho thú lơn hay nhỏ đều được, dùng được cho cả chó, mèo:\r\n>> Nhanh chóng tiêu diệt và xua đuổi ve ghẻ ký sinh trùng trên thú\r\n>> Tinh chất thảo dược không có mùi khó chịu\r\n>> Có hai loại cho chó & mèo vui lòng lựa chọn kỹ\r\n>> Tiện dụng, tận hưởng niềm vui', 'thuoc.jpg', 69000, 'LSP04'),
('SP06', 'Sữa tắm cho thú cưng 5 trong 1 – Vimeshampo 300m', 'KH001', 100, '[GIỚI THIỆU] Sữa tắm cho thú cưng 5 trong 1 – Vimeshampo 300ml\r\n[MÔ TẢ] Sữa tắm cho thú cưng, tiện dụng, an toàn, bạn sẽ không còn lo các vấn đề do ký sinh trùng, mùi hôi nữa\r\n[CÔNG DỤNG]\r\n>> Cho mọi lứa tuổi chó mèo\r\n>> Làm sạch lông, Sạch ve ghẻ, bọ chét, rận tai\r\n>> Chống rụng lông.\r\n>> Khử mùi hôi.\r\n>> Dưỡng lông, giúp lông siêu mượt.\r\n>> Phòng ngừa nhiễm ghẻ và nấm da.\r\n>> Giá hợp lý và chất lượng cao', 'suatam.jpg', 45900, 'LSP02'),
('SP07', 'Cần câu mèo dây thep có chuông - Cần câu 002', 'H004', 80, '[GIỚI THIỆU] Cần câu cho mèo dây thép (mẫu giao ngẫu nhiên)\r\nSợi dây: Dây thép\r\nThú nhử: bông & lông vũ\r\n\r\n[MÔ TẢ & CÔNG DỤNG]\r\nCần Câu là đồ chơi cho mèo ngộ nghĩnh, dễ thương, với chú cá giả, chuột giả hoặc lông vũ buộc vào cần câu, bạn sẽ tha hồ đùa giỡn với chú mèo của mình\r\n \r\nDùng để chơi đùa cùng thú cưng của bạn.\r\n \r\nĐủ màu sắc ngộ nghĩnh đáng yêu, thu hút thú cưng nhà bạn chơi đùa cùng Cần câu mèo, tăng cương khả năng vận động hoạt bát của thú cưng.\r\n Chi tiết: 1 cần + 1 hình thú, kích thích thú cưng vờn bắt', 'cancau.jpg', 26900, 'LSP05'),
('SP08', 'Chuồng Gấp Gọn Cho Chó Mèo, Lồng Xếp Sơn Tĩnh Điện Tặng Kèm Khay Vệ Sinh', 'H002', 20, 'Chuồng Gấp Gọn Cho Chó Mèo, Lồng Gấp Gọn Sơn Tĩnh Điện Tặng Kèm Khay Vệ Sinh\r\nMàu sắc: ĐEN , XANH DƯƠNG, HỒNG\r\nShop có 3 loại kích thước:\r\n- 50 x 35 x 40cm ( chó mèo dưới 5kg)\r\n- 60 x 42 x 44cm (chó mèo dưới 7kg)\r\n- 70 x 50 x 50cm (chó mèo dưới 10kg)', 'chuong.jpg', 179000, 'LSP06'),
('SP09', 'Ly rửa chân thú nhỏ', 'H001', 34, 'Với các đầu gai cao su mềm, nhẹ nhàng lấy đi chất bẩn, bùn đât cho chó mèo.\r\nKhông làm đau thú. Chỉ cần sọt chân vào là xong, sạch sẽ chất bẩn\r\nKhông mất công lấy tay rửa từng ngón chân cho thú nữa\r\nDễ sử dụng, chất lượng cao', 'chan.jpg', 189000, 'LSP02');

